from estatgojpapi.models import GetStatsDataResponse
from estatgojpapi.processors import process_statistical_data

from .fixtures import sample_get_stats_data_json


def test_process_statistical_data() -> None:
    expected = [
        {
            "スマホ利用時間": {"code": "100", "name": "総数", "level": "1", "unit": "人"},
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "人",
            "value": "4000",
        },
        {
            "スマホ利用時間": {"code": "100", "name": "総数", "level": "1", "unit": "人"},
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "人",
            "value": "2000",
        },
        {
            "スマホ利用時間": {"code": "100", "name": "総数", "level": "1", "unit": "人"},
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "人",
            "value": "2000",
        },
        {
            "スマホ利用時間": {
                "code": "110",
                "name": "30分くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "10.0",
        },
        {
            "スマホ利用時間": {
                "code": "110",
                "name": "30分くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "9.0",
        },
        {
            "スマホ利用時間": {
                "code": "110",
                "name": "30分くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "11.0",
        },
        {
            "スマホ利用時間": {
                "code": "120",
                "name": "1時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "20.0",
        },
        {
            "スマホ利用時間": {
                "code": "120",
                "name": "1時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "19.0",
        },
        {
            "スマホ利用時間": {
                "code": "120",
                "name": "1時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "21.0",
        },
        {
            "スマホ利用時間": {
                "code": "130",
                "name": "2時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "30.0",
        },
        {
            "スマホ利用時間": {
                "code": "130",
                "name": "2時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "29.0",
        },
        {
            "スマホ利用時間": {
                "code": "130",
                "name": "2時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "31.0",
        },
        {
            "スマホ利用時間": {
                "code": "140",
                "name": "3時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "25.0",
        },
        {
            "スマホ利用時間": {
                "code": "140",
                "name": "3時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "24.0",
        },
        {
            "スマホ利用時間": {
                "code": "140",
                "name": "3時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "26.0",
        },
        {
            "スマホ利用時間": {
                "code": "150",
                "name": "4時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "10.0",
        },
        {
            "スマホ利用時間": {
                "code": "150",
                "name": "4時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "9.0",
        },
        {
            "スマホ利用時間": {
                "code": "150",
                "name": "4時間くらい",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "11.0",
        },
        {
            "スマホ利用時間": {"code": "160", "name": "5時間以上", "level": "2", "unit": "%", "parent_code": "100"},
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "5.0",
        },
        {
            "スマホ利用時間": {"code": "160", "name": "5時間以上", "level": "2", "unit": "%", "parent_code": "100"},
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "4.0",
        },
        {
            "スマホ利用時間": {"code": "160", "name": "5時間以上", "level": "2", "unit": "%", "parent_code": "100"},
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "6.0",
        },
        {
            "スマホ利用時間": {
                "code": "170",
                "name": "まったく使わない",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "1.0",
        },
        {
            "スマホ利用時間": {
                "code": "170",
                "name": "まったく使わない",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "0.9",
        },
        {
            "スマホ利用時間": {
                "code": "170",
                "name": "まったく使わない",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "1.1",
        },
        {
            "スマホ利用時間": {
                "code": "180",
                "name": "わからない",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "100", "name": "総数", "level": "1"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "0.5",
        },
        {
            "スマホ利用時間": {
                "code": "180",
                "name": "わからない",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "110", "name": "男性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "0.4",
        },
        {
            "スマホ利用時間": {
                "code": "180",
                "name": "わからない",
                "level": "2",
                "unit": "%",
                "parent_code": "100",
            },
            "性別": {"code": "120", "name": "女性", "level": "2", "parent_code": "100"},
            "時間軸(年度次)": {"code": "2021000000", "name": "2021年度", "level": "1"},
            "unit": "%",
            "value": "0.6",
        },
    ]

    actual = process_statistical_data(
        GetStatsDataResponse.model_validate(sample_get_stats_data_json).get_stats_data.statistical_data
    )

    assert actual == expected
